In [13]:
# @title 텐서만들기
import torch

data_list =[[1,2],[2,3]]
print(type(data_list))
tensor = torch.tensor(data_list)
print(type(tensor))
tensor

<class 'list'>
<class 'torch.Tensor'>


tensor([[1, 2],
        [2, 3]])

In [14]:
# t = torch.tensor([
#     [[1, 2, 3],
#      [4, 5, 6]],
#
#     [[7, 8, 9],
#      [10, 11, 12]]
# ])
# print(t.ndim)
# print(t.shape)

3
torch.Size([2, 2, 3])


In [4]:
print(f'data type: P{tensor.dtype}')
print(f'number of demensions: {tensor.ndim}')
print(f'shape : {tensor.shape}')
print(f'device : {tensor.device}')
print(f'requires_grad: {tensor.requires_grad}') # 자동 미분을 기록할지 여부 결정

data type: Ptorch.int64
number of demensions: 2
shape : torch.Size([2, 2])
device : cpu
requires_grad: False


In [5]:
import torch
import numpy as np

data_np = np.array([[1, 2], [3, 4]])


tensor_np = torch.tensor(data_np)
print(tensor_np)          # 텐서 값 출력
print(type(tensor_np))    # 파이썬 객체의 타입
print(tensor_np.dtype)    # 원소 데이터 타입 (dtype)
print(tensor_np.type())   # 텐서의 dtype + 장치(device) 정보 문자열
# 3. 왜 int64 vs LongTensor?
# 	•	torch.int64 ↔ torch.LongTensor : 같은 자료형입니다.
# 	•	PyTorch에서 LongTensor라는 이름은 int64 텐서를 가리키는 클래스 이름이에요.
# 	•	즉, int64 == LongTensor
# 	•	비슷하게:
# 	•	torch.float32 ↔ torch.FloatTensor
# 	•	torch.int32 ↔ torch.IntTensor


tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.int64
torch.LongTensor


In [15]:
#방법 2:torch.from_numpy()

tensor_from_numpy = torch.from_numpy(data_np)
tensor_from_numpy

<class 'torch.Tensor'>


In [7]:
# 방법 3: torch.as_tensor()

tensor_as_tensor = torch.as_tensor(data_np)
tensor_as_tensor

tensor([[1, 2],
        [3, 4]])

In [8]:
data_np[0,0] = -1
print(f'torch.tensor : {tensor_np}')
print(f'torch.from_numpy : {tensor_from_numpy}')
print(f'torch.as_tensor : {tensor_as_tensor}')

torch.tensor : tensor([[1, 2],
        [3, 4]])
torch.from_numpy : tensor([[-1,  2],
        [ 3,  4]])
torch.as_tensor : tensor([[-1,  2],
        [ 3,  4]])


In [9]:
# 1. torch.tensor()
np_array = np.array([1, 2, 3])
t1 = torch.tensor(np_array)
np_array[0] = 999
print("torch.tensor():", t1)   # 영향 없음 (복사)

# 2. torch.from_numpy()
np_array = np.array([1, 2, 3])
t2 = torch.from_numpy(np_array)
np_array[0] = 999
print("torch.from_numpy():", t2)   # 영향 받음 (공유)

# 3. torch.as_tensor()
np_array = np.array([1, 2, 3])
t3 = torch.as_tensor(np_array)
np_array[0] = 999
print("torch.as_tensor() with numpy:", t3)  # 영향 받음 (공유)

py_list = [1, 2, 3]
t4 = torch.as_tensor(py_list)
py_list[0] = 999
print("torch.as_tensor() with list:", t4)  # 영향 없음 (복사)

torch.tensor(): tensor([1, 2, 3])
torch.from_numpy(): tensor([999,   2,   3])
torch.as_tensor() with numpy: tensor([999,   2,   3])
torch.as_tensor() with list: tensor([1, 2, 3])


In [10]:
print(tensor.dtype)
tensor = torch.tensor([1,1.5])
print(tensor.dtype)

torch.int64
torch.float32


In [22]:
tensor = torch.tensor([1,2,3], dtype=torch.float64)
tensor.dtype

torch.float64

In [25]:
tensor = torch.tensor([1.2, 3.7, 5.6])
tensor.dtype
int_tensor = tensor.to(torch.int32) # GPU, CPU 변경때도 사용, 타입형 변환때도 사용
print(int_tensor.dtype)
print(int_tensor.int())
a = tensor.tolist() # list형태로 변환
print(a)
# to변환과 int() 모두 똑같음.

torch.int32
tensor([1, 3, 5], dtype=torch.int32)
[1.2000000476837158, 3.700000047683716, 5.599999904632568]


In [49]:
int_tensor.to('cpu') # 안에 cuda, mps, cpu 추가하기

tensor([1, 3, 5], dtype=torch.int32)

In [68]:
torch.rand(2,3) #차원수대로 만들기
torch.rand([2,3])
torch.rand((2,3))

tensor([[0.5770, 0.4606, 0.6949],
        [0.6513, 0.6167, 0.2055]])

In [83]:
a = torch.randn(2,5)
a

tensor([[-0.9590, -0.7492,  0.6660, -2.0082,  2.8522],
        [ 0.8545, -0.0770,  1.0627,  0.8929,  0.3871]])

In [90]:
import numpy as np
import torch

data_list = [
    [1, 1],
    [-1, -1],
]
data_np = np.array(
    [
        [3, 4],
        [5, 6]
    ]
)

# 여기에 코드를 작성하세요.
tensor_from_list = torch.as_tensor(data_list)
tensor_from_np_array = torch.from_numpy(data_np)
print(tensor_from_list)
print(tensor_from_np_array)

tensor([[ 1,  1],
        [-1, -1]])
tensor([[3, 4],
        [5, 6]])


# 텐서의 변환과 연산

In [32]:
# 텐서 -> 넘파이

tensor = torch.ones(2,2)
print(tensor.dtype)

np_array = tensor.numpy() # 메모리 공유
np_array

np_array2 = np.array(tensor) # 메모리 공유 X
np_array2

tensor[0,0] = -0
print(np_array)
print("\n")
print(np_array2)

torch.float32
[[0. 1.]
 [1. 1.]]


[[1. 1.]
 [1. 1.]]


In [114]:
a = torch.tensor([[1,2],
                  [3,4]])
b = torch.tensor([[1,1],
                  [2,2],
                  ])
# a+b
# torch.add(a,b)

# element wise
# print(a*b)
# torch.mul(a,b)


# matrix mul
a@b


tensor([[ 5,  5],
        [11, 11]])

In [109]:
a = torch.tensor([[1,2],
                  [3,4],
                  [5,6],
                  [7,8],
                  ])
b = torch.tensor([[1,0,0],
                  [0,0,1],
                  [1,1,0]])

# shpae이 같아야지 elementwise * 가능.
# shape이 다르고 a의 열과 b의 행이 같다면 @ 연산.
print(f"a shpae: {a.shape}")
print(f"b shape: {b.shape}")


a shpae: torch.Size([4, 2])
b shape: torch.Size([3, 3])


In [36]:
tensor_int = torch.tensor([1,2], dtype=torch.int32)
tensor_float = torch.tensor([3,4], dtype=torch.float32)

print(tensor_int+tensor_float.int())
print(tensor_int * tensor_float)

tensor([4, 6], dtype=torch.int32)
tensor([3., 8.])


In [40]:
# 행렬 연산은 무조건 타입을 맞춰야함.

tensor_int = torch.tensor([1,2], dtype=torch.int32)
tensor_float = torch.tensor(
    [
        [3,1],
        [4,1]],
    dtype=torch.int32
)
tensor_int @ tensor_float

tensor([11,  3], dtype=torch.int32)

# Tensor Indexing

In [132]:

import torch

tensor0 = torch.tensor(
    [
        [1, 1],
        [-1, -1]
    ]
)
tensor1 = torch.tensor(
    [
        [1, 1],
        [0, 0]
    ]
)
tensor2 = torch.tensor(
    [
        [1, -1],
        [1, -1]
    ]
)

# 여기에 코드를 작성하세요.

result_1 = tensor0 + tensor1

result_2 = result_1 @ tensor2

result_2[:,0] += 2
result_2[:,1] -= 2


final_np_array = result_2.numpy()
# 테스트 코드
print(final_np_array)

[[ 6 -6]
 [ 0  0]]


In [142]:
x = torch.randn(2,3,4)
print(x)

tensor([[[-0.3071,  1.1345,  1.8737,  1.6328],
         [ 0.2665, -0.6037, -1.4174, -0.6891],
         [ 1.0029, -0.6465, -0.5703, -0.8099]],

        [[-0.0299,  1.1823,  0.7459,  1.3892],
         [-0.0419, -1.4741,  1.9645,  0.8037],
         [ 0.6932,  0.8383,  1.4936, -0.5620]]])


In [144]:
x = x.permute(2,0,1)
# 2번째가 첫번재로, 0번째가 마지막으로, 첫번째가 3으로
# 4, 2, 3으로 바뀌게 됨 -> x.shape 가 4,2,3으로 바꾸겠다.
# 보통 이미지의 채널이 맨 마지막으로 가있는데 h,w,c 순서.
# 이걸 나중에 c, h, w 순서로 바꿔야할때 이렇게 바꿔줘야함.
x

tensor([[[-0.3071, -0.0299],
         [ 1.1345,  1.1823],
         [ 1.8737,  0.7459],
         [ 1.6328,  1.3892]],

        [[ 0.2665, -0.0419],
         [-0.6037, -1.4741],
         [-1.4174,  1.9645],
         [-0.6891,  0.8037]],

        [[ 1.0029,  0.6932],
         [-0.6465,  0.8383],
         [-0.5703,  1.4936],
         [-0.8099, -0.5620]]])

In [149]:
x1 = torch.randn(2,3)
x2 = x1.T

In [151]:
x = torch.randn(1,28,1,28)
x

tensor([[[[-4.3566e-01, -1.3358e-01,  4.9709e-01, -3.5091e-01,  1.5515e-01,
           -1.8640e+00,  4.3157e-01,  2.0919e+00,  2.4716e+00, -2.2736e-01,
           -1.0977e+00, -5.9702e-01,  1.1072e-01,  9.0082e-02,  1.3828e-01,
           -4.7674e-01, -3.3919e-01,  1.1141e+00,  5.2973e-01, -6.7624e-01,
           -6.6123e-01,  5.0734e-01, -1.2317e+00,  2.7494e-01, -2.7709e-01,
           -3.5564e-01, -7.6755e-01,  9.0806e-01]],

         [[-7.4522e-01, -5.0687e-01, -2.6124e-02, -1.2885e+00,  1.3940e-01,
           -1.2550e-02, -1.4114e+00, -1.3326e+00,  1.9911e-01,  1.6913e-01,
           -8.0631e-01,  1.1214e+00, -9.0976e-01, -1.4978e+00,  7.7029e-01,
           -6.1144e-01,  4.8686e-01,  2.0324e-01,  6.4861e-01,  1.0717e+00,
           -2.9677e-01, -1.4288e-01, -9.0797e-01, -1.1865e+00, -6.2577e-01,
           -1.8363e-01, -4.4152e-01, -3.2139e-02]],

         [[ 7.1624e-01, -7.7253e-02, -2.6526e-01,  7.6643e-01,  1.9324e+00,
           -4.7480e-01,  2.8587e-01,  2.4742e+00,  1.1495e

In [154]:
res0 = x.squeeze() # dim = 1 것 삭제하기
print(res0.shape)


torch.Size([28, 28])


In [155]:
x = torch.randn(28,28)
x

tensor([[ 8.1487e-01, -1.3945e+00, -5.5358e-01,  2.5793e+00,  1.0833e+00,
         -1.8909e-01, -3.6629e-01, -3.9038e-01,  8.1689e-01, -1.1690e+00,
          2.3206e-01, -1.1271e+00, -1.1155e+00, -9.5974e-01, -7.4481e-01,
          5.9548e-01, -7.2616e-01, -8.7447e-01,  3.0787e-01,  8.5307e-01,
          9.3053e-01,  5.4318e-01,  1.3207e+00, -2.3712e+00,  7.8992e-01,
         -5.0359e-01,  5.4721e-01, -1.3557e-01],
        [-8.4120e-01, -1.0559e+00,  1.3465e+00,  1.3725e+00, -2.1409e+00,
         -1.8106e+00,  1.1301e+00, -7.1438e-01, -6.1078e-01,  8.0363e-01,
          1.4181e-01, -2.6695e-01, -1.3341e-01, -3.2400e-01,  9.7349e-01,
          2.3064e-01, -1.0799e+00, -8.5442e-01, -1.5353e+00,  1.0247e+00,
         -7.3489e-01, -1.6189e+00,  1.0269e+00, -9.6342e-01,  8.6389e-01,
          1.3740e+00,  6.4228e-01,  8.2115e-01],
        [ 1.0478e+00,  7.6765e-02, -9.9781e-01,  1.0128e+00,  6.8465e-01,
          2.4462e+00, -4.5028e-01, -7.5654e-01, -5.8382e-01, -2.0386e-01,
          1.36

In [159]:
# 원래는 28x28 행렬이었는데, 1번 index에 차원 하난를 추가하겠다.
res0 = x.unsqueeze(1)
print(res0.shape)

torch.Size([28, 1, 28])


# view() & contiguous() 개념
- 원소의 개수를 유지하고 Reshape와 비슷

- view는 원본과 메모리를 공유함
- w()는 copy를 만들지 않고 원본 텐서의 메모리 구조만 재해석 → 더 빠름.
- reshape()는 경우에 따라 copy가 생길 수 있음 → 느려질 수 있음.

⸻

3. 정리
- w(): 빠름, 메모리 연속적이어야 함. (안 맞으면 에러), 원본과 메모리를 공유함
-  reshape(): 유연함, copy가 생길 수도 있음. (안전빵)

In [164]:
x = torch.rand(3,4)
result = x.view(2,6)
result.shape

torch.Size([2, 6])

In [172]:
x = torch.ones(2,3)
x_view = x.view(-1)
print(x_view)
x[0,0] = 0
x_view

tensor([1., 1., 1., 1., 1., 1.])


tensor([0., 1., 1., 1., 1., 1.])

In [174]:
x.is_contiguous()
# x에 있는 element들이 연속적으로 붙어있어야함.
# True가 나온다면 view 사용가능.


True

# 여러 텐서 합치기

In [182]:
x = torch.zeros(2,3)
y = torch.ones(2,3)

cat0 = torch.cat([x,y], dim=1)
print(cat0, "\n\n")
cat0 = torch.cat([x,y], dim = 0)
print(cat0)

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]]) 


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [191]:
stack_res = torch.stack([x,y], dim=0)
cat_res = torch.cat([x,y,],dim=0)


print(stack_res.shape) # 차원을 추가해서 쌓기 [2,2]끼리 스택을 한다면[2,2,2]이됨
print(stack_res)
print(cat_res)
print(cat_res.shape)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])


In [225]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
print(x[1][2])
x.split(1,dim=0) #size, di

tensor(8)


(tensor([[1, 2, 3, 4, 5]]), tensor([[ 6,  7,  8,  9, 10]]))

# chunk vs split

In [231]:
import torch

x = torch.tensor([[1,2,3,4,5],
                  [6,7,8,9,10]])

# split
print(x.split(2, dim=1))   # 2개씩 나누기
# (tensor([[1, 2, 3, 4, 5]]), tensor([[ 6,  7,  8,  9, 10]]))

# chunk
print(x.chunk(2, dim=1))   # 결과과 2개의 덩어리로 나오도록
# (tensor([[1, 2, 3, 4, 5]]), tensor([[ 6,  7,  8,  9, 10]]))

(tensor([[1, 2],
        [6, 7]]), tensor([[3, 4],
        [8, 9]]), tensor([[ 5],
        [10]]))
(tensor([[1, 2, 3],
        [6, 7, 8]]), tensor([[ 4,  5],
        [ 9, 10]]))


In [239]:
tensor.to('cpu').device
# tensor.to('mps').device

device(type='mps', index=0)